language: node_js

deploy:
  - provider: heroku
    api_key:
      secure: $API_KEY
    app: wordspeech
    on: releases/web
  - provider: heroku
    api_key:
      secure: $API_KEY
    app: wordspeechapi
    on: releases/api