language: node_js

deploy:
  - provider: heroku
    api_key:
      secure: 56b9f837-2eb8-4903-802f-256a2b5dec05
    app: wordspeech
    on: releases/web
  - provider: heroku
    api_key:
      secure: $API_KEY
    app: wordspeechapi
    on: releases/api