FROM node:slim

ENV NODE_ENV=production 
ENV TTS_HOST=http://wordspeechapi.herokuapp.com/
WORKDIR /app/web/

ADD package.json .

RUN yarn install

COPY . .

EXPOSE 3001

ENTRYPOINT ["yarn", "start"]

